Repository Thom-x/docker-fr24feed-piaware-dump1090, pull requests merged in 2021-03, with the labels that each got.

#45 Better UI integration with FlightRadar24 in addition to FlightAware
  .gitignore
  Dockerfile
  patch/README.md
  patch/flightradar24.patch
  patch/refresh.sh
  patch/resources/fr24-logo.svg
  root/etc/confd/html/templates/config.js.tmpl
Labels: bump:minor, enhancement

#50 chore: dummy commit for test
  README.md
Labels: bump:patch

#51 feat(map): add open weather map and rainviewer.com layers
  Dockerfile
  README.md
  root/etc/confd/layers/conf.d/layers.toml
  root/etc/confd/layers/templates/layers.js.tmpl
  root/etc/cont-init.d/04-confd-layers
  root/etc/cont-init.d/05-upintheair
Labels: bump:patch, enhancement

#49 Better UI integration with FlightRadar24 in addition to FlightAware - continued
  .gitignore
  README.md
  docker-compose.yml
  patch/flightradar24.patch
  patch/refresh.sh
  root/etc/confd/html/templates/config.js.tmpl
  root/etc/cont-init.d/03-confd-html
Labels: bump:patch, enhancement

#54 arm64
  .github/workflows/docker-publish.yml
  .github/workflows/pull-request-publish.yml
  .github/workflows/pull-request.yml
  build/fr24feed.sh
  build/s6-overlay.sh
Labels: bump:patch

#48 feat(piaware): bump piaware/dump1090 to v5.0
  Dockerfile
  README.md
  patch/flightradar24.patch
  patch/refresh.sh
  root/etc/confd/html/templates/config.js.tmpl
Labels: bump:minor, enhancement

#55 chore(CI): try building different images arch in parallel
  .github/workflows/docker-publish.yml
  .github/workflows/pull-request-publish.yml
  .github/workflows/pull-request.yml
Labels: enhancement
