Repository Thom-x/docker-fr24feed-piaware-dump1090, pull requests merged in 2022-03, with the labels that each got.

#76 chore(build): do only one big RUN and one big COPY, to decrease image size
  Dockerfile
Labels: enhancement, bump:patch

#78 doc(77): add warn about owm price, fix temp layer
  README.md
  root/etc/confd/layers/templates/layers.js.tmpl
Labels: bump:patch

#80 asdbexchange support, work in progress
  Dockerfile
  README.md
  docker-compose.yml
  root/etc/s6-overlay/s6-rc.d/adsbexchange-bundle/contents.d/adsbexchange-feed
  root/etc/s6-overlay/s6-rc.d/adsbexchange-bundle/contents.d/adsbexchange-mlat
  root/etc/s6-overlay/s6-rc.d/adsbexchange-bundle/contents.d/adsbexchange-stats
  root/etc/s6-overlay/s6-rc.d/adsbexchange-bundle/type
  root/etc/s6-overlay/s6-rc.d/adsbexchange-feed/dependencies.d/conf-adsbexchange
  root/etc/s6-overlay/s6-rc.d/adsbexchange-feed/dependencies.d/dump1090
  root/etc/s6-overlay/s6-rc.d/adsbexchange-feed/finish
  root/etc/s6-overlay/s6-rc.d/adsbexchange-feed/run
  root/etc/s6-overlay/s6-rc.d/adsbexchange-feed/type
  root/etc/s6-overlay/s6-rc.d/adsbexchange-mlat/dependencies.d/adsbexchange-feed
  root/etc/s6-overlay/s6-rc.d/adsbexchange-mlat/dependencies.d/conf-adsbexchange
  root/etc/s6-overlay/s6-rc.d/adsbexchange-mlat/dependencies.d/dump1090
  root/etc/s6-overlay/s6-rc.d/adsbexchange-mlat/finish
  root/etc/s6-overlay/s6-rc.d/adsbexchange-mlat/run
  root/etc/s6-overlay/s6-rc.d/adsbexchange-mlat/type
  root/etc/s6-overlay/s6-rc.d/adsbexchange-stats/dependencies.d/adsbexchange-feed
  root/etc/s6-overlay/s6-rc.d/adsbexchange-stats/dependencies.d/conf-adsbexchange
  root/etc/s6-overlay/s6-rc.d/adsbexchange-stats/dependencies.d/dump1090
  root/etc/s6-overlay/s6-rc.d/adsbexchange-stats/finish
  root/etc/s6-overlay/s6-rc.d/adsbexchange-stats/run
  root/etc/s6-overlay/s6-rc.d/adsbexchange-stats/type
  root/etc/s6-overlay/s6-rc.d/conf-adsbexchange/script
  root/etc/s6-overlay/s6-rc.d/conf-adsbexchange/type
  root/etc/s6-overlay/s6-rc.d/conf-adsbexchange/up
  root/etc/s6-overlay/s6-rc.d/user/contents.d/adsbexchange-bundle
Labels: bump:minor

#81 chore: use env to start or not adsbexchange (avoid error at startup)
  Dockerfile
  README.md
  docker-compose.yml
  root/etc/s6-overlay/s6-rc.d/adsbexchange-feed/run
  root/etc/s6-overlay/s6-rc.d/adsbexchange-mlat/run
  root/etc/s6-overlay/s6-rc.d/adsbexchange-stats/run
  root/etc/s6-overlay/s6-rc.d/conf-adsbexchange/script
  screenshot.png
Labels: enhancement, bump:patch

#84 fix(#83): fix planefinder for arm
  Dockerfile
  build/fr24feed.sh
  build/planefinder.sh
Labels: bug, bump:patch
